# Update assets branch when assets.json change

name: Download Assets

on:
  push:
    branches: [ master ]
    paths:
    - 'assets.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout main branch
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: deploy to page branch
      run: npm ci && npm run deploy
      env:
        DEPLOY_TYPE: ASSETS
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
