# Build Backend API when master branch change

name: Build Assets

on:
  push:
    branches: [ assets ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy to page branch
      uses: miaowm5/rmproject2@action
      with:
        deploy_type: 'assets'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
