# Build React front page when frontend branch change

name: Build Frontend

on:
  push:
    branches: [ master ]
    paths:
    - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: build react
      run: npm ci && npm run build
      working-directory: ./frontend
    - name: deploy to page branch
      run: npm ci && npm run deploy
      env:
        DEPLOY_TYPE: FRONTEND
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
